---
- name: Add Zulu.org JDK repository key
  apt_key: keyserver=keyserver.ubuntu.com key=0x219BD9C9
  when: corda_java == "openjdk"

- name: Add Zulu.org JDK repository
  apt_repository:
    repo: http://repos.azulsystems.com/ubuntu stable main
    state: present
  when: corda_java == "openjdk"

- name: Update APT cache
  apt: update_cache=yes

- name: Install os packages
  apt: pkg="{{ item }}" state=present
  with_items:
    - ntp

- name: Install OpenJDK (Zulu build)
  apt: pkg="{{ item }}" state=present
  when: corda_java == "openjdk"
  with_items:
    - zulu-8

- name: Install LXML (required for Maven Central download)
  apt: pkg=python-lxml state=present
  when: corda_source == "maven"

